// Code generated by go generate; DO NOT EDIT.
// 2021-02-17 11:03:59.205597887 +0100 CET m=+0.000212742

package apiclient

import (
	"context"
	"errors"
	"io"
	"net/http"
	"strings"
	"testing"
)

//go:generate go run ./internal/gencallapitest/...

