// Code generated by go generate; DO NOT EDIT.
// 2021-02-17 13:52:34.540324253 +0100 CET m=+0.000248991

package apiclient

import (
	"context"
	"errors"
	"io"
	"net/http"
	"strings"
	"testing"
)

//go:generate go run ./internal/gencallapitest/...

