// Code generated by go generate; DO NOT EDIT.
// 2021-02-17 09:01:57.369928373 +0100 CET m=+0.000245845

package apiclient

import "context"

//go:generate go run ./internal/genclientcall/...

// CheckReportID calls the CheckReportID API.
func (c *Client) CheckReportID(ctx context.Context, req *CheckReportIDRequest) (*CheckReportIDResponse, error) {
	return NewCheckReportIDAPI(c).Call(ctx, req)
}

// CheckIn calls the CheckIn API.
func (c *Client) CheckIn(ctx context.Context, req *CheckInRequest) (*CheckInResponse, error) {
	return NewCheckInAPI(c).Call(ctx, req)
}

// Login calls the Login API.
func (c *Client) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return NewLoginAPI(c).Call(ctx, req)
}

// MeasurementMeta calls the MeasurementMeta API.
func (c *Client) MeasurementMeta(ctx context.Context, req *MeasurementMetaRequest) (*MeasurementMetaResponse, error) {
	return NewMeasurementMetaAPI(c).Call(ctx, req)
}

// Register calls the Register API.
func (c *Client) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return NewRegisterAPI(c).Call(ctx, req)
}

// TestHelpers calls the TestHelpers API.
func (c *Client) TestHelpers(ctx context.Context, req *TestHelpersRequest) (TestHelpersResponse, error) {
	return NewTestHelpersAPI(c).Call(ctx, req)
}

// PsiphonConfig calls the PsiphonConfig API.
func (c *Client) PsiphonConfig(ctx context.Context, req *PsiphonConfigRequest) (PsiphonConfigResponse, error) {
	return NewPsiphonConfigAPI(c).Call(ctx, req)
}

// TorTargets calls the TorTargets API.
func (c *Client) TorTargets(ctx context.Context, req *TorTargetsRequest) (TorTargetsResponse, error) {
	return NewTorTargetsAPI(c).Call(ctx, req)
}

// URLs calls the URLs API.
func (c *Client) URLs(ctx context.Context, req *URLsRequest) (*URLsResponse, error) {
	return NewURLsAPI(c).Call(ctx, req)
}

// OpenReport calls the OpenReport API.
func (c *Client) OpenReport(ctx context.Context, req *OpenReportRequest) (*OpenReportResponse, error) {
	return NewOpenReportAPI(c).Call(ctx, req)
}

// SubmitMeasurement calls the SubmitMeasurement API.
func (c *Client) SubmitMeasurement(ctx context.Context, req *SubmitMeasurementRequest) (*SubmitMeasurementResponse, error) {
	return NewSubmitMeasurementAPI(c).Call(ctx, req)
}
