// Code generated by go generate; DO NOT EDIT.
// 2021-02-17 10:17:41.781663495 +0100 CET m=+0.000230586

package apiclient

import "context"

//go:generate go run ./internal/genclientcall/...

// CheckReportID calls the CheckReportID API.
func (c *Client) CheckReportID(ctx context.Context, req *CheckReportIDRequest) (*CheckReportIDResponse, error) {
	return newCheckReportIDAPI(c).Call(ctx, req)
}

// CheckIn calls the CheckIn API.
func (c *Client) CheckIn(ctx context.Context, req *CheckInRequest) (*CheckInResponse, error) {
	return newCheckInAPI(c).Call(ctx, req)
}

// MeasurementMeta calls the MeasurementMeta API.
func (c *Client) MeasurementMeta(ctx context.Context, req *MeasurementMetaRequest) (*MeasurementMetaResponse, error) {
	return newMeasurementMetaAPI(c).Call(ctx, req)
}

// TestHelpers calls the TestHelpers API.
func (c *Client) TestHelpers(ctx context.Context, req *TestHelpersRequest) (TestHelpersResponse, error) {
	return newTestHelpersAPI(c).Call(ctx, req)
}

// PsiphonConfig calls the PsiphonConfig API.
func (c *Client) PsiphonConfig(ctx context.Context, req *PsiphonConfigRequest) (PsiphonConfigResponse, error) {
	return newPsiphonConfigAPI(c).Call(ctx, req)
}

// TorTargets calls the TorTargets API.
func (c *Client) TorTargets(ctx context.Context, req *TorTargetsRequest) (TorTargetsResponse, error) {
	return newTorTargetsAPI(c).Call(ctx, req)
}

// URLs calls the URLs API.
func (c *Client) URLs(ctx context.Context, req *URLsRequest) (*URLsResponse, error) {
	return newURLsAPI(c).Call(ctx, req)
}

// OpenReport calls the OpenReport API.
func (c *Client) OpenReport(ctx context.Context, req *OpenReportRequest) (*OpenReportResponse, error) {
	return newOpenReportAPI(c).Call(ctx, req)
}

// SubmitMeasurement calls the SubmitMeasurement API.
func (c *Client) SubmitMeasurement(ctx context.Context, req *SubmitMeasurementRequest) (*SubmitMeasurementResponse, error) {
	return newSubmitMeasurementAPI(c).Call(ctx, req)
}
