// Code generated by go generate; DO NOT EDIT.
// 2021-02-17 19:37:57.844705816 +0100 CET m=+0.089861575

package apiclient

import (
	"context"
	"errors"
	"io"
	"net/http"
	"strings"
	"testing"

	"github.com/bassosimone/apiclient/internal/imodel"
	"github.com/bassosimone/apiclient/model"
)

//go:generate go run ./internal/cmd/generator

func TestCheckReportIDInvalidURL(t *testing.T) {
	api := &checkReportIDAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.CheckReportIDRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckReportIDWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &checkReportIDAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckReportIDRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckReportIDWithNewRequestErr(t *testing.T) {
	api := &checkReportIDAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.CheckReportIDRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckReportIDWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &checkReportIDAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckReportIDRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckReportIDWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &checkReportIDAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckReportIDRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckReportIDWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &checkReportIDAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.CheckReportIDRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckReportIDRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &checkReportIDAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckReportIDRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestCheckReportIDMandatoryFields(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableLiteralNull{},
	}}
	api := &checkReportIDAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckReportIDRequest{} // deliberately empty
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrEmptyField) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckInInvalidURL(t *testing.T) {
	api := &checkInAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.CheckInRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckInWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &checkInAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckInRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckInMarshalErr(t *testing.T) {
	api := &checkInAPI{
		BaseURL: "https://ps1.ooni.io",
		marshal: func(v interface{}) ([]byte, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.CheckInRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckInWithNewRequestErr(t *testing.T) {
	api := &checkInAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.CheckInRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckInWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &checkInAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckInRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckInWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &checkInAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckInRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckInWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &checkInAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.CheckInRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestCheckInRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &checkInAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.CheckInRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestLoginInvalidURL(t *testing.T) {
	api := &loginAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &imodel.LoginRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestLoginWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &loginAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &imodel.LoginRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestLoginMarshalErr(t *testing.T) {
	api := &loginAPI{
		BaseURL: "https://ps1.ooni.io",
		marshal: func(v interface{}) ([]byte, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &imodel.LoginRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestLoginWithNewRequestErr(t *testing.T) {
	api := &loginAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &imodel.LoginRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestLoginWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &loginAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &imodel.LoginRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestLoginWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &loginAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &imodel.LoginRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestLoginWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &loginAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &imodel.LoginRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestLoginRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &loginAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &imodel.LoginRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestMeasurementMetaInvalidURL(t *testing.T) {
	api := &measurementMetaAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.MeasurementMetaRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestMeasurementMetaWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &measurementMetaAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.MeasurementMetaRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestMeasurementMetaWithNewRequestErr(t *testing.T) {
	api := &measurementMetaAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.MeasurementMetaRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestMeasurementMetaWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &measurementMetaAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.MeasurementMetaRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestMeasurementMetaWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &measurementMetaAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.MeasurementMetaRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestMeasurementMetaWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &measurementMetaAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.MeasurementMetaRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestMeasurementMetaRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &measurementMetaAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.MeasurementMetaRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestMeasurementMetaMandatoryFields(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableLiteralNull{},
	}}
	api := &measurementMetaAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.MeasurementMetaRequest{} // deliberately empty
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrEmptyField) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestRegisterInvalidURL(t *testing.T) {
	api := &registerAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &imodel.RegisterRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestRegisterWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &registerAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &imodel.RegisterRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestRegisterMarshalErr(t *testing.T) {
	api := &registerAPI{
		BaseURL: "https://ps1.ooni.io",
		marshal: func(v interface{}) ([]byte, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &imodel.RegisterRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestRegisterWithNewRequestErr(t *testing.T) {
	api := &registerAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &imodel.RegisterRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestRegisterWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &registerAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &imodel.RegisterRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestRegisterWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &registerAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &imodel.RegisterRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestRegisterWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &registerAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &imodel.RegisterRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestRegisterRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &registerAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &imodel.RegisterRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestTestHelpersInvalidURL(t *testing.T) {
	api := &testHelpersAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.TestHelpersRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTestHelpersWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &testHelpersAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TestHelpersRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTestHelpersWithNewRequestErr(t *testing.T) {
	api := &testHelpersAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.TestHelpersRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTestHelpersWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &testHelpersAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TestHelpersRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTestHelpersWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &testHelpersAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TestHelpersRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTestHelpersWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &testHelpersAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.TestHelpersRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTestHelpersRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &testHelpersAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TestHelpersRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestTestHelpersResponseLiteralNull(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableLiteralNull{},
	}}
	api := &testHelpersAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TestHelpersRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrJSONLiteralNull) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigInvalidURL(t *testing.T) {
	api := &psiphonConfigAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigWithMissingAuthorizer(t *testing.T) {
	api := &psiphonConfigAPI{
		BaseURL: "https://ps1.ooni.io",
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMissingAuthorizer) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &psiphonConfigAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigWithNewRequestErr(t *testing.T) {
	api := &psiphonConfigAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &psiphonConfigAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &psiphonConfigAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &psiphonConfigAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &psiphonConfigAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestPsiphonConfigResponseLiteralNull(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableLiteralNull{},
	}}
	api := &psiphonConfigAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrJSONLiteralNull) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestPsiphonConfigWithFailingAuthorizer(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &psiphonConfigAPI{
		Authorizer: &failingAuthorizer{},
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.PsiphonConfigRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsInvalidURL(t *testing.T) {
	api := &torTargetsAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsWithMissingAuthorizer(t *testing.T) {
	api := &torTargetsAPI{
		BaseURL: "https://ps1.ooni.io",
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMissingAuthorizer) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &torTargetsAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsWithNewRequestErr(t *testing.T) {
	api := &torTargetsAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &torTargetsAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &torTargetsAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &torTargetsAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &torTargetsAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestTorTargetsResponseLiteralNull(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableLiteralNull{},
	}}
	api := &torTargetsAPI{
		Authorizer: newStaticAuthorizer("fakeToken"),
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrJSONLiteralNull) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestTorTargetsWithFailingAuthorizer(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &torTargetsAPI{
		Authorizer: &failingAuthorizer{},
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.TorTargetsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestURLsInvalidURL(t *testing.T) {
	api := &urlsAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.URLsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestURLsWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &urlsAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.URLsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestURLsWithNewRequestErr(t *testing.T) {
	api := &urlsAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.URLsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestURLsWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &urlsAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.URLsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestURLsWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &urlsAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.URLsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestURLsWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &urlsAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.URLsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestURLsRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &urlsAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.URLsRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestOpenReportInvalidURL(t *testing.T) {
	api := &openReportAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.OpenReportRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestOpenReportWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &openReportAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.OpenReportRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestOpenReportMarshalErr(t *testing.T) {
	api := &openReportAPI{
		BaseURL: "https://ps1.ooni.io",
		marshal: func(v interface{}) ([]byte, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.OpenReportRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestOpenReportWithNewRequestErr(t *testing.T) {
	api := &openReportAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.OpenReportRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestOpenReportWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &openReportAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.OpenReportRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestOpenReportWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &openReportAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.OpenReportRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestOpenReportWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &openReportAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.OpenReportRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestOpenReportRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &openReportAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.OpenReportRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestSubmitMeasurementInvalidURL(t *testing.T) {
	api := &submitMeasurementAPI{
		BaseURL: "\t", // invalid
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err == nil || !strings.HasSuffix(err.Error(), "invalid control character in URL") {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestSubmitMeasurementWithHTTPErr(t *testing.T) {
	clnt := &mockableHTTPClient{Err: errMocked}
	api := &submitMeasurementAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestSubmitMeasurementMarshalErr(t *testing.T) {
	api := &submitMeasurementAPI{
		BaseURL: "https://ps1.ooni.io",
		marshal: func(v interface{}) ([]byte, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestSubmitMeasurementWithNewRequestErr(t *testing.T) {
	api := &submitMeasurementAPI{
		BaseURL: "https://ps1.ooni.io",
		NewRequest: func(ctx context.Context, method, URL string, body io.Reader) (*http.Request, error) {
			return nil, errMocked
		},
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestSubmitMeasurementWith400(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{StatusCode: 400}}
	api := &submitMeasurementAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, ErrHTTPFailure) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestSubmitMeasurementWithResponseBodyReadErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableBodyWithFailure{},
	}}
	api := &submitMeasurementAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestSubmitMeasurementWithUnmarshalFailure(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &submitMeasurementAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		unmarshal: func(b []byte, v interface{}) error {
			return errMocked
		},
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestSubmitMeasurementRoundTrip(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableEmptyBody{},
	}}
	api := &submitMeasurementAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("expected non-nil resp")
	}
}

func TestSubmitMeasurementTemplateParseErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableLiteralNull{},
	}}
	api := &submitMeasurementAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		newTemplate: func(name string) textTemplate {
			return &templateParseError{}
		},
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}

func TestSubmitMeasurementTemplateExecuteErr(t *testing.T) {
	clnt := &mockableHTTPClient{Resp: &http.Response{
		StatusCode: 200,
		Body:       &mockableLiteralNull{},
	}}
	api := &submitMeasurementAPI{
		BaseURL:    "https://ps1.ooni.io",
		HTTPClient: clnt,
		newTemplate: func(name string) textTemplate {
			return &templateExecuteError{}
		},
	}
	ctx := context.Background()
	req := &model.SubmitMeasurementRequest{}
	ff := &fakeFill{}
	ff.fill(req)
	resp, err := api.call(ctx, req)
	if !errors.Is(err, errMocked) {
		t.Fatal("not the error we expected", err)
	}
	if resp != nil {
		t.Fatal("expected nil resp")
	}
}
