// Code generated by go generate; DO NOT EDIT.
// 2021-02-16 16:20:51.482285699 +0100 CET m=+0.000256084

package apiclient

//go:generate go run ./internal/gennew/...

// NewCheckReportIDAPI creates a new instance of CheckReportIDAPI.
func NewCheckReportIDAPI(clnt *Client) (*CheckReportIDAPI, error) {
	api := &CheckReportIDAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewCheckInAPI creates a new instance of CheckInAPI.
func NewCheckInAPI(clnt *Client) (*CheckInAPI, error) {
	api := &CheckInAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewLoginAPI creates a new instance of LoginAPI.
func NewLoginAPI(clnt *Client) (*LoginAPI, error) {
	api := &LoginAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewMeasurementMetaAPI creates a new instance of MeasurementMetaAPI.
func NewMeasurementMetaAPI(clnt *Client) (*MeasurementMetaAPI, error) {
	api := &MeasurementMetaAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewRegisterAPI creates a new instance of RegisterAPI.
func NewRegisterAPI(clnt *Client) (*RegisterAPI, error) {
	api := &RegisterAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewTestHelpersAPI creates a new instance of TestHelpersAPI.
func NewTestHelpersAPI(clnt *Client) (*TestHelpersAPI, error) {
	api := &TestHelpersAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewPsiphonConfigAPI creates a new instance of PsiphonConfigAPI.
func NewPsiphonConfigAPI(clnt *Client) (*PsiphonConfigAPI, error) {
	api := &PsiphonConfigAPI{
		Authorizer: clnt,
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewTorTargetsAPI creates a new instance of TorTargetsAPI.
func NewTorTargetsAPI(clnt *Client) (*TorTargetsAPI, error) {
	api := &TorTargetsAPI{
		Authorizer: clnt,
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewURLsAPI creates a new instance of URLsAPI.
func NewURLsAPI(clnt *Client) (*URLsAPI, error) {
	api := &URLsAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewOpenReportAPI creates a new instance of OpenReportAPI.
func NewOpenReportAPI(clnt *Client) (*OpenReportAPI, error) {
	api := &OpenReportAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}

// NewSubmitMeasurementAPI creates a new instance of SubmitMeasurementAPI.
func NewSubmitMeasurementAPI(clnt *Client) (*SubmitMeasurementAPI, error) {
	api := &SubmitMeasurementAPI{
		BaseURL:    clnt.BaseURL,
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api, nil
}
