// Code generated by go generate; DO NOT EDIT.
// 2021-02-16 18:01:12.851253215 +0100 CET m=+0.000183357

package apiclient

//go:generate go run ./internal/gennew/...

// NewCheckReportIDAPI creates a new instance of CheckReportIDAPI. This factory
// always returns a valid, non-nil instance.
func NewCheckReportIDAPI(clnt *Client) *CheckReportIDAPI {
	api := &CheckReportIDAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewCheckInAPI creates a new instance of CheckInAPI. This factory
// always returns a valid, non-nil instance.
func NewCheckInAPI(clnt *Client) *CheckInAPI {
	api := &CheckInAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewLoginAPI creates a new instance of LoginAPI. This factory
// always returns a valid, non-nil instance.
func NewLoginAPI(clnt *Client) *LoginAPI {
	api := &LoginAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewMeasurementMetaAPI creates a new instance of MeasurementMetaAPI. This factory
// always returns a valid, non-nil instance.
func NewMeasurementMetaAPI(clnt *Client) *MeasurementMetaAPI {
	api := &MeasurementMetaAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewRegisterAPI creates a new instance of RegisterAPI. This factory
// always returns a valid, non-nil instance.
func NewRegisterAPI(clnt *Client) *RegisterAPI {
	api := &RegisterAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewTestHelpersAPI creates a new instance of TestHelpersAPI. This factory
// always returns a valid, non-nil instance.
func NewTestHelpersAPI(clnt *Client) *TestHelpersAPI {
	api := &TestHelpersAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewPsiphonConfigAPI creates a new instance of PsiphonConfigAPI. This factory
// always returns a valid, non-nil instance.
func NewPsiphonConfigAPI(clnt *Client) *PsiphonConfigAPI {
	api := &PsiphonConfigAPI{
		Authorizer: clnt,
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewTorTargetsAPI creates a new instance of TorTargetsAPI. This factory
// always returns a valid, non-nil instance.
func NewTorTargetsAPI(clnt *Client) *TorTargetsAPI {
	api := &TorTargetsAPI{
		Authorizer: clnt,
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewURLsAPI creates a new instance of URLsAPI. This factory
// always returns a valid, non-nil instance.
func NewURLsAPI(clnt *Client) *URLsAPI {
	api := &URLsAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewOpenReportAPI creates a new instance of OpenReportAPI. This factory
// always returns a valid, non-nil instance.
func NewOpenReportAPI(clnt *Client) *OpenReportAPI {
	api := &OpenReportAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}

// NewSubmitMeasurementAPI creates a new instance of SubmitMeasurementAPI. This factory
// always returns a valid, non-nil instance.
func NewSubmitMeasurementAPI(clnt *Client) *SubmitMeasurementAPI {
	api := &SubmitMeasurementAPI{
		BaseURL:    clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent:  clnt.UserAgent,
	}
	return api
}
