// Code generated by go generate; DO NOT EDIT.
// 2021-02-17 09:49:09.773467848 +0100 CET m=+0.000138202

package apiclient

//go:generate go run ./internal/gennewapi/...

// newCheckReportIDAPI creates a new instance of checkReportIDAPI. This factory
// always returns a valid, non-nil instance.
func newCheckReportIDAPI(clnt *Client) *checkReportIDAPI {
	api := &checkReportIDAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newCheckInAPI creates a new instance of checkInAPI. This factory
// always returns a valid, non-nil instance.
func newCheckInAPI(clnt *Client) *checkInAPI {
	api := &checkInAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newLoginAPI creates a new instance of loginAPI. This factory
// always returns a valid, non-nil instance.
func newLoginAPI(clnt *Client) *loginAPI {
	api := &loginAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newMeasurementMetaAPI creates a new instance of measurementMetaAPI. This factory
// always returns a valid, non-nil instance.
func newMeasurementMetaAPI(clnt *Client) *measurementMetaAPI {
	api := &measurementMetaAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newRegisterAPI creates a new instance of registerAPI. This factory
// always returns a valid, non-nil instance.
func newRegisterAPI(clnt *Client) *registerAPI {
	api := &registerAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newTestHelpersAPI creates a new instance of testHelpersAPI. This factory
// always returns a valid, non-nil instance.
func newTestHelpersAPI(clnt *Client) *testHelpersAPI {
	api := &testHelpersAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newPsiphonConfigAPI creates a new instance of psiphonConfigAPI. This factory
// always returns a valid, non-nil instance.
func newPsiphonConfigAPI(clnt *Client) *psiphonConfigAPI {
	api := &psiphonConfigAPI{
		Authorizer: clnt,
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newTorTargetsAPI creates a new instance of torTargetsAPI. This factory
// always returns a valid, non-nil instance.
func newTorTargetsAPI(clnt *Client) *torTargetsAPI {
	api := &torTargetsAPI{
		Authorizer: clnt,
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newURLsAPI creates a new instance of urlsAPI. This factory
// always returns a valid, non-nil instance.
func newURLsAPI(clnt *Client) *urlsAPI {
	api := &urlsAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newOpenReportAPI creates a new instance of openReportAPI. This factory
// always returns a valid, non-nil instance.
func newOpenReportAPI(clnt *Client) *openReportAPI {
	api := &openReportAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

// newSubmitMeasurementAPI creates a new instance of submitMeasurementAPI. This factory
// always returns a valid, non-nil instance.
func newSubmitMeasurementAPI(clnt *Client) *submitMeasurementAPI {
	api := &submitMeasurementAPI{
		BaseURL: clnt.baseURL(),
		HTTPClient: clnt.HTTPClient,
		UserAgent: clnt.UserAgent,
	}
	return api
}

