// This script generates newresponse.go.
package main

import (
	"os"
	"time"

	"github.com/bassosimone/apiclient/internal/apimodel"
	"github.com/bassosimone/apiclient/internal/fatalx"
	"github.com/bassosimone/apiclient/internal/fmtx"
	"github.com/bassosimone/apiclient/internal/reflectx"
)

func gettype(in interface{}) string {
	sinfo, err := reflectx.NewStructInfo(in)
	fatalx.OnError(err, "reflectx.NewStructInfo failed")
	return sinfo.TypeName()
}

func genbeginfunc(filep *os.File, desc *apimodel.Descriptor) {
	typename := gettype(desc.Response)
	fmtx.Fprintf(filep, "// New%s creates a new %s\n", typename, typename)
	fmtx.Fprintf(filep, "func New%s", typename)
	fmtx.Fprint(filep, "(resp *http.Response, err error)")
	fmtx.Fprintf(filep, " (*%s, error) {\n", typename)
}

func genparse(filep *os.File, desc *apimodel.Descriptor) {
	typename := gettype(desc.Response)
	fmtx.Fprint(filep, "\tif err != nil {\n")
	fmtx.Fprint(filep, "\t\treturn nil, err\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprint(filep, "\tif resp.StatusCode != 200 {\n")
	fmtx.Fprint(filep, "\t\treturn nil, errors.New(\"apiclient: http request failed\")\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprint(filep, "\tdefer resp.Body.Close()\n")
	fmtx.Fprint(filep, "\treader := io.LimitReader(resp.Body, 4<<20)\n")
	fmtx.Fprint(filep, "\tdata, err := ioutil.ReadAll(reader)\n")
	fmtx.Fprint(filep, "\tif err != nil {\n")
	fmtx.Fprint(filep, "\t\treturn nil, err\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprintf(filep, "\tvar out %s\n", typename)
	fmtx.Fprint(filep, "\tif err := json.Unmarshal(data, &out); err != nil {\n")
	fmtx.Fprint(filep, "\t\treturn nil, err\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprint(filep, "\treturn &out, nil\n")
}

func genendfunc(filep *os.File) {
	fmtx.Fprintf(filep, "}\n\n")
}

func genapi(filep *os.File, desc *apimodel.Descriptor) {
	genbeginfunc(filep, desc)
	genparse(filep, desc)
	genendfunc(filep)
}

func main() {
	filep, err := os.Create("newresponse.go")
	fatalx.OnError(err, "os.Create failed")

	fmtx.Fprint(filep, "// Code generated by go generate; DO NOT EDIT.\n")
	fmtx.Fprintf(filep, "// %v\n\n", time.Now())
	fmtx.Fprint(filep, "package apiclient\n\n")
	fmtx.Fprint(filep, "import (\n")
	fmtx.Fprint(filep, "\t\"encoding/json\"\n")
	fmtx.Fprint(filep, "\t\"errors\"\n")
	fmtx.Fprint(filep, "\t\"io/ioutil\"\n")
	fmtx.Fprint(filep, "\t\"io\"\n")
	fmtx.Fprint(filep, "\t\"net/http\"\n")
	fmtx.Fprint(filep, ")\n\n")

	for _, descr := range apimodel.Descriptors {
		genapi(filep, &descr)
	}

	err = filep.Close()
	fatalx.OnError(err, "filep.Close failed")
}
