// This script generates api.go
package main

import (
	"strings"
	"time"

	"github.com/bassosimone/apiclient/internal/apimodel"
	"github.com/bassosimone/apiclient/internal/fmtx"
	"github.com/bassosimone/apiclient/internal/osx"
	"github.com/bassosimone/apiclient/internal/reflectx"
)

func getapiame(in interface{}) string {
	name := reflectx.Must(reflectx.NewTypeValueInfo(in)).TypeName()
	name = strings.Replace(name, "Request", "", 1)
	name = strings.Replace(name, "Response", "", 1)
	return name
}

func genbeginfunc(filep osx.File, desc *apimodel.Descriptor) {
	resp := reflectx.Must(reflectx.NewTypeValueInfo(desc.Response))
	req := reflectx.Must(reflectx.NewTypeValueInfo(desc.Request)).TypeName()
	apiname := getapiame(desc.Response)
	fmtx.Fprintf(filep, "// %s%s implements the %s %s API\n", desc.Method, apiname, desc.Method, desc.URLPath.Value)
	fmtx.Fprintf(filep, "func (c Client) %s%s", desc.Method, apiname)
	fmtx.Fprintf(filep, "(ctx context.Context, in *%s)", req)
	fmtx.Fprintf(filep, " (%s, error) {\n", resp.AsReturnType())
}

func gencall(filep osx.File, desc *apimodel.Descriptor) {
	resp := reflectx.Must(reflectx.NewTypeValueInfo(desc.Response)).TypeName()
	req := reflectx.Must(reflectx.NewTypeValueInfo(desc.Request)).TypeName()
	fmtx.Fprintf(filep, "\treq, err := new%s(ctx, c.BaseURL, in)\n", req)
	fmtx.Fprint(filep, "\tif err != nil {\n")
	fmtx.Fprint(filep, "\t\treturn nil, err\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprint(filep, "\tif c.Accept != \"\" {\n")
	fmtx.Fprint(filep, "\t\treq.Header.Add(\"Accept\", c.Accept)\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprint(filep, "\tif c.Authorization != \"\" {\n")
	fmtx.Fprint(filep, "\t\treq.Header.Add(\"Authorization\", c.Authorization)\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprint(filep, "\treq.Header.Add(\"User-Agent\", c.UserAgent)\n")
	fmtx.Fprintf(filep, "\treturn new%s(c.HTTPClient.Do(req))\n", resp)
}

func genendfunc(filep osx.File) {
	fmtx.Fprintf(filep, "}\n\n")
}

func genapi(filep osx.File, desc *apimodel.Descriptor) {
	genbeginfunc(filep, desc)
	gencall(filep, desc)
	genendfunc(filep)
}

func main() {
	filep := osx.MustCreate("api.go")
	defer filep.Close()

	fmtx.Fprint(filep, "// Code generated by go generate; DO NOT EDIT.\n")
	fmtx.Fprintf(filep, "// %v\n\n", time.Now())
	fmtx.Fprint(filep, "package apiclient\n\n")
	fmtx.Fprint(filep, "import \"context\"\n\n")

	fmtx.Fprint(filep, "//go:generate go run ./internal/genapi/...\n\n")

	for _, descr := range apimodel.Descriptors {
		genapi(filep, &descr)
	}
}
