// This script generates api.go
package main

import (
	"strings"
	"time"

	"github.com/bassosimone/apiclient/internal/apimodel"
	"github.com/bassosimone/apiclient/internal/fatalx"
	"github.com/bassosimone/apiclient/internal/fmtx"
	"github.com/bassosimone/apiclient/internal/osx"
	"github.com/bassosimone/apiclient/internal/reflectx"
)

func gettype(in interface{}) string {
	sinfo, err := reflectx.NewStructInfo(in)
	fatalx.OnError(err, "reflectx.NewStructInfo failed")
	return sinfo.TypeName()
}

func getapiame(in interface{}) string {
	name := gettype(in)
	name = strings.Replace(name, "Request", "", 1)
	name = strings.Replace(name, "Response", "", 1)
	return name
}

func genbeginfunc(filep osx.File, desc *apimodel.Descriptor) {
	resp := gettype(desc.Response)
	req := gettype(desc.Request)
	apiname := getapiame(desc.Response)
	fmtx.Fprintf(filep, "// %s%s implements the %s %s API\n", desc.Method, apiname, desc.Method, desc.URLPath)
	fmtx.Fprintf(filep, "func (c Client) %s%s", desc.Method, apiname)
	fmtx.Fprintf(filep, "(ctx context.Context, in *%s)", req)
	fmtx.Fprintf(filep, " (*%s, error) {\n", resp)
}

func gencall(filep osx.File, desc *apimodel.Descriptor) {
	resp := gettype(desc.Response)
	req := gettype(desc.Request)
	fmtx.Fprintf(filep, "\treq, err := New%s(ctx, c.BaseURL, in)\n", req)
	fmtx.Fprint(filep, "\tif err != nil {\n")
	fmtx.Fprint(filep, "\t\treturn nil, err\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprintf(filep, "\treturn New%s(c.HTTPClient.Do(req))\n", resp)
}

func genendfunc(filep osx.File) {
	fmtx.Fprintf(filep, "}\n\n")
}

func genapi(filep osx.File, desc *apimodel.Descriptor) {
	genbeginfunc(filep, desc)
	gencall(filep, desc)
	genendfunc(filep)
}

func main() {
	filep := osx.MustCreate("api.go")
	defer filep.Close()

	fmtx.Fprint(filep, "// Code generated by go generate; DO NOT EDIT.\n")
	fmtx.Fprintf(filep, "// %v\n\n", time.Now())
	fmtx.Fprint(filep, "package apiclient\n\n")
	fmtx.Fprint(filep, "import \"context\"\n\n")

	for _, descr := range apimodel.Descriptors {
		genapi(filep, &descr)
	}
}
