package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"time"

	"github.com/bassosimone/apiclient/internal/fatalx"
)

func isRequestOrResponse(decl ast.Decl) bool {
	gendecl, good := decl.(*ast.GenDecl)
	if !good {
		return false
	}
	switch gendecl.Tok {
	case token.TYPE, token.VAR:
		return true
	default:
		return false
	}
}

func main() {
	outfile := flag.String("outfile", "datamodel.go", "Output file")
	pkgdir := flag.String("pkg", "", "Package directory path")
	flag.Parse()

	filep, err := os.Create(*outfile)
	fatalx.OnError(err, "os.Create failed")

	_, err = filep.Write([]byte(
		"// Code generated by go generate; DO NOT EDIT.\n"))
	fatalx.OnError(err, "filep.Write failed")

	_, err = fmt.Fprintf(filep, "// %+v\n\n", time.Now())
	fatalx.OnError(err, "filep.Write failed")

	_, err = filep.Write([]byte("package apiclient\n\n"))
	fatalx.OnError(err, "filep.Write failed")

	fset := token.NewFileSet()

	pkgs, err := parser.ParseDir(fset, *pkgdir, nil, parser.ParseComments)
	fatalx.OnError(err, "parser.ParseDir failed")

	model := pkgs["datamodel"]
	fatalx.IfNil(model, "cannot find the datamodel package")

	for _, fdata := range model.Files {
		for _, decl := range fdata.Decls {
			if !isRequestOrResponse(decl) {
				continue
			}

			err = format.Node(filep, fset, decl)
			fatalx.OnError(err, "format.Node failed")

			_, err = filep.Write([]byte("\n\n"))
			fatalx.OnError(err, "filep.Write failed")
		}
	}

	err = filep.Close()
	fatalx.OnError(err, "filep.Close failed")
}
