// This script generates newrequest.go
package main

import (
	"os"
	"reflect"
	"strings"
	"time"

	"github.com/bassosimone/apiclient/internal/apimodel"
	"github.com/bassosimone/apiclient/internal/fatalx"
	"github.com/bassosimone/apiclient/internal/fmtx"
	"github.com/bassosimone/apiclient/internal/reflectx"
)

func gettype(in interface{}) string {
	sinfo, err := reflectx.NewStructInfo(in)
	fatalx.OnError(err, "reflectx.NewStructInfo failed")
	return sinfo.TypeName()
}

func gettags(in interface{}, tagName string) []*reflectx.FieldInfo {
	sinfo, err := reflectx.NewStructInfo(in)
	fatalx.OnError(err, "reflectx.NewStructInfo failed")
	return sinfo.AllFieldsWithTag(tagName)
}

func genbeginfunc(filep *os.File, desc *apimodel.Descriptor) {
	typename := gettype(desc.Request)
	fmtx.Fprintf(filep, "// New%s creates a new %s\n", typename, typename)
	fmtx.Fprintf(filep, "func New%s", typename)
	fmtx.Fprint(filep, "(ctx context.Context, ")
	fmtx.Fprint(filep, "baseURL string, ")
	fmtx.Fprintf(filep, "req *%s)", typename)
	fmtx.Fprint(filep, " (*http.Request, error) {\n")
}

func genurlpath(filep *os.File, desc *apimodel.Descriptor) {
	if !strings.Contains(desc.URLPath, "{{ ") {
		fmtx.Fprintf(filep, "\tURL.Path = \"%s\"\n", desc.URLPath)
		return
	}
	fmtx.Fprintf(filep, "\ttmpl, err := template.New(\"urlpath\").Parse(\"%s\")\n", desc.URLPath)
	fmtx.Fprint(filep, "\tif err != nil {\n")
	fmtx.Fprint(filep, "\t\treturn nil, err\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprint(filep, "\tvar urlpath strings.Builder\n")
	fmtx.Fprint(filep, "\terr = tmpl.Execute(&urlpath, req)\n")
	fmtx.Fprint(filep, "\tif err != nil {\n")
	fmtx.Fprint(filep, "\t\treturn nil, err\n")
	fmtx.Fprint(filep, "\t}\n")
	fmtx.Fprint(filep, "\tURL.Path = urlpath.String()\n")
}

func genqueryforstring(filep *os.File, field *reflectx.FieldInfo) {
	name := field.Self.Name
	query := field.Self.Tag.Get("query")
	if field.Self.Tag.Get("mandatory") == "true" {
		fmtx.Fprintf(filep, "\tif req.%s == \"\" {\n", name)
		fmtx.Fprint(filep, "\t\treturn nil, errors.New(")
		fmtx.Fprintf(filep, "\"apiclient: empty %s field\")\n", name)
		fmtx.Fprintf(filep, "\t}\n")
		fmtx.Fprintf(filep, "\tquery.Add(\"%s\", ", query)
		fmtx.Fprintf(filep, "req.%s)\n", name)
		return
	}
	fmtx.Fprintf(filep, "\tif req.%s != \"\" {\n", name)
	fmtx.Fprintf(filep, "\t\tquery.Add(\"%s\", ", query)
	fmtx.Fprintf(filep, "req.%s)\n", name)
	fmtx.Fprintf(filep, "\t}\n")
}

func genqueryforbool(filep *os.File, field *reflectx.FieldInfo) {
	name := field.Self.Name
	query := field.Self.Tag.Get("query")
	// mandatory does not make much sense for a boolean field
	fmtx.Fprintf(filep, "\tif req.%s {\n", name)
	fmtx.Fprintf(filep, "\t\tquery.Add(\"%s\", \"true\")\n", query)
	fmtx.Fprintf(filep, "\t}\n")
}

func genqueryforint64(filep *os.File, field *reflectx.FieldInfo) {
	name := field.Self.Name
	query := field.Self.Tag.Get("query")
	// mandatory does not make much sense for an integer field
	fmtx.Fprintf(filep, "\tif req.%s != 0 {\n", name)
	fmtx.Fprintf(filep, "\t\tquery.Add(\"%s\", fmtx.Sprintf(\"%%d\", req.%s))\n", query, name)
	fmtx.Fprintf(filep, "\t}\n")
}

func genquery(filep *os.File, desc *apimodel.Descriptor) {
	if desc.Method == "POST" {
		return
	}
	fields := gettags(desc.Request, "query")
	if fields == nil {
		return
	}
	fmtx.Fprint(filep, "\tquery := url.Values{}\n")
	for _, field := range fields {
		switch field.Self.Type.Kind() {
		case reflect.String:
			genqueryforstring(filep, field)
		case reflect.Bool:
			genqueryforbool(filep, field)
		case reflect.Int64:
			genqueryforint64(filep, field)
		default:
			panic("query: unsupported field type")
		}
	}
	fmtx.Fprint(filep, "\tURL.RawQuery = query.Encode()\n")
}

func gencreaterequest(filep *os.File, desc *apimodel.Descriptor) {
	if desc.Method == "POST" {
		fmtx.Fprint(filep, "\tbody, err := json.Marshal(req)\n")
		fmtx.Fprint(filep, "\tif err != nil {\n")
		fmtx.Fprint(filep, "\t\treturn nil, err\n")
		fmtx.Fprint(filep, "\t}\n")
	}
	fmtx.Fprint(filep, "\treturn http.NewRequestWithContext(")
	fmtx.Fprintf(filep, "ctx, \"%s\", URL.String(), ", desc.Method)
	if desc.Method != "POST" {
		fmtx.Fprint(filep, "nil)\n")
		return
	}
	fmtx.Fprint(filep, "bytes.NewReader(body))\n")
}

func genmakeurl(filep *os.File, desc *apimodel.Descriptor) {
	fmtx.Fprint(filep, "\tURL, err := url.Parse(baseURL)\n")
	fmtx.Fprint(filep, "\tif err != nil {\n")
	fmtx.Fprint(filep, "\t\treturn nil, err\n")
	fmtx.Fprint(filep, "\t}\n")
}

func genendfunc(filep *os.File) {
	fmtx.Fprintf(filep, "}\n\n")
}

func genapi(filep *os.File, desc *apimodel.Descriptor) {
	genbeginfunc(filep, desc)
	genmakeurl(filep, desc)
	genurlpath(filep, desc)
	genquery(filep, desc)
	gencreaterequest(filep, desc)
	genendfunc(filep)
}

func main() {
	filep, err := os.Create("newrequest.go")
	fatalx.OnError(err, "os.Create failed")

	fmtx.Fprint(filep, "// Code generated by go generate; DO NOT EDIT.\n")
	fmtx.Fprintf(filep, "// %v\n\n", time.Now())
	fmtx.Fprint(filep, "package apiclient\n\n")
	fmtx.Fprint(filep, "import (\n")
	fmtx.Fprint(filep, "\t\"bytes\"\n")
	fmtx.Fprint(filep, "\t\"context\"\n")
	fmtx.Fprint(filep, "\t\"encoding/json\"\n")
	fmtx.Fprint(filep, "\t\"errors\"\n")
	fmtx.Fprint(filep, "\t\"fmt\"\n")
	fmtx.Fprint(filep, "\t\"text/template\"\n")
	fmtx.Fprint(filep, "\t\"net/http\"\n")
	fmtx.Fprint(filep, "\t\"net/url\"\n")
	fmtx.Fprint(filep, "\t\"strings\"\n")
	fmtx.Fprint(filep, ")\n\n")

	for _, descr := range apimodel.Descriptors {
		genapi(filep, &descr)
	}

	err = filep.Close()
	fatalx.OnError(err, "filep.Close failed")
}
