// Command genapimodel generates apimodel.go
package main

import (
	"time"

	"github.com/bassosimone/apiclient/internal/apimodel"
	"github.com/bassosimone/apiclient/internal/fmtx"
	"github.com/bassosimone/apiclient/internal/osx"
)

func main() {
	filep := osx.MustCreate("apimodel.go")
	defer filep.Close()

	fmtx.Fprint(filep, "// Code generated by go generate; DO NOT EDIT.\n")
	fmtx.Fprintf(filep, "// %v\n\n", time.Now())
	fmtx.Fprint(filep, "package apiclient\n\n")
	fmtx.Fprint(filep, "import (\n")
	fmtx.Fprint(filep, "\t\"bytes\"\n")
	fmtx.Fprint(filep, "\t\"context\"\n")
	fmtx.Fprint(filep, "\t\"encoding/json\"\n")
	fmtx.Fprint(filep, "\t\"fmt\"\n")
	fmtx.Fprint(filep, "\t\"io/ioutil\"\n")
	fmtx.Fprint(filep, "\t\"io\"\n")
	fmtx.Fprint(filep, "\t\"net/http\"\n")
	fmtx.Fprint(filep, "\t\"net/url\"\n")
	fmtx.Fprint(filep, "\t\"strings\"\n")
	fmtx.Fprint(filep, "\n")
	fmtx.Fprint(filep, "\t\"github.com/bassosimone/apiclient/internal/imodel\"\n")
	fmtx.Fprint(filep, "\t\"github.com/bassosimone/apiclient/model\"\n")
	fmtx.Fprint(filep, ")\n\n")

	fmtx.Fprint(filep, "//go:generate go run ./internal/genapimodel/...\n\n")

	for _, desc := range apimodel.Descriptors {
		fmtx.Fprintf(filep, desc.GenClientCall())
		fmtx.Fprintf(filep, desc.GenAPIType())
		fmtx.Fprintf(filep, desc.GenNewAPI())
		fmtx.Fprintf(filep, desc.GenAPICall())
		fmtx.Fprintf(filep, desc.GenNewRequest())
		fmtx.Fprintf(filep, desc.GenNewResponse())
	}
}
