package main

import (
	"time"

	"github.com/bassosimone/apiclient/internal/apimodel"
)

func genAPIModel() {
	filep := MustCreate("apimodel.go")
	defer filep.Close()

	Fprint(filep, "// Code generated by go generate; DO NOT EDIT.\n")
	Fprintf(filep, "// %v\n\n", time.Now())
	Fprint(filep, "package apiclient\n\n")
	Fprint(filep, "import (\n")
	Fprint(filep, "\t\"bytes\"\n")
	Fprint(filep, "\t\"context\"\n")
	Fprint(filep, "\t\"encoding/json\"\n")
	Fprint(filep, "\t\"io/ioutil\"\n")
	Fprint(filep, "\t\"io\"\n")
	Fprint(filep, "\t\"net/http\"\n")
	Fprint(filep, "\t\"net/url\"\n")
	Fprint(filep, "\t\"strings\"\n")
	Fprint(filep, "\n")
	Fprint(filep, "\t\"github.com/bassosimone/apiclient/internal/imodel\"\n")
	Fprint(filep, "\t\"github.com/bassosimone/apiclient/model\"\n")
	Fprint(filep, ")\n\n")

	Fprint(filep, "//go:generate go run ./internal/generator/...\n\n")

	for _, desc := range apimodel.Descriptors {
		Fprintf(filep, desc.GenClientCall())
		Fprintf(filep, desc.GenAPIType())
		Fprintf(filep, desc.GenNewAPI())
		Fprintf(filep, desc.GenAPICall())
		Fprintf(filep, desc.GenNewRequest())
		Fprintf(filep, desc.GenNewResponse())
	}
}
